import { Button } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex-1 flex flex-col justify-center items-center">
        <h1 className="text-6xl">
          Welcome to{" "}
          <a className="text-[#ec8c69] hover:underline " href="#">
            DesWeb
          </a>
        </h1>
        <Link href={'/setup'}>
        <Button
          className="bg-gradient-to-r from-[#ed6ea0] to-[#ec8c69] hover:bg-gradient-to-l"
          mt={50}
        >
          Get Started
        </Button>
        </Link>
      </main>
    </div>
  );
};

export default Home;
